#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/adapty.module

#!name=Adapty

#!desc=Adapty

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% api.adapty.io

[Script]

Adapty=type=http-response,pattern=https://api.adapty.io/api/v1/sdk/analytics/profiles,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/adapty.js