#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/adblockpro.module

#!name=AdblockPro

#!desc=AdblockPro

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% api.adblockpro.app

[Script]

AdblockPro=type=http-response,pattern=api.adblockpro.app/verify,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/adblockpro.js