#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/adguardpro.module

#!name=AdGuardPro

#!desc=AdGuardPro

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% mobile-api.adguard.org

[Script]

AdGuardPro=type=http-response,pattern=^https:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt\/(.*?),requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/adguardpro.js