#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/alightmotion.module

#!name=AlightMotion

#!desc=AlightMotion

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% us-central1-alight-creative.cloudfunctions.net

[Script]

AlightMotion=type=http-response,pattern=https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/alightmotion.js