#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/autorc.module

#!name=AutoRC

#!desc=AutoRC

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% api.revenuecat.com

[Script]

AutoRC=type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/autorc.js