#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/esound.module

#!name=eSound

#!desc=eSound

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% api.esound.app

[Script]

eSound=type=http-response,pattern=api.esound.app/account,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/esound.js