#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/itunes.module

#!name=iTunes

#!desc=iTunes

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% buy.itunes.apple.com

[Script]

iTunes=type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/itunes.js