#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/muslimpro.module

#!name=MuslimPro

#!desc=MuslimPro

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% us-central1-muslim-pro-app.cloudfunctions.net

[Script]

MuslimPro=type=http-response,pattern=us-central1-muslim-pro-app.cloudfunctions.net/GetUserPremiumInfo,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/muslimpro.js