#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/myfitnesspal.module

#!name=MyFitnessPal

#!desc=MyFitnessPal

#!homepage=https://whatshub.top

#!author=NobyDa

[MITM]

hostname= %APPEND% premium-api.myfitnesspal.com

[Script]

MyFitnessPal=type=http-response,pattern=https://premium-api.myfitnesspal.com/v3/subscriptions/MFP/*,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/myfitnesspal.js