#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/pdfviewer.module

#!name=PDF Viewer

#!desc=PDF Viewer

#!homepage=https://whatshub.top

#!author= 89996462

[MITM]

hostname = %APPEND% api.revenuecat.com

[Script]

PDF Viewer=type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/v1\/subscribers.+,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/pdfviewer.js