#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/picsart.module

#!name=PicsArt

#!desc=PicsArt

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% api.picsart.com

[Script]

PicsArt=type=http-request,pattern=https://api.picsart.com/gw-v2/shop/subscription/apple/purchases,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/picsart.js