#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/qonversion.module

#!name=Qonversion

#!desc=Qonversion

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% api.qonversion.io

[Script]

Qonversion=type=http-response,pattern=api.qonversion.io/v1/user/init,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/qonversion.js