#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/readdle.module

#!name=Readdle

#!desc=Readdle

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% license.pdfexpert.com

[Script]

Readdle=type=http-response,pattern=https:\/\/license\.pdfexpert\.com\/api\/2\.0\/(calendarslite|pdfexpert6|documents)\/subscription\/(refresh|check),requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/readdle.js