#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/sandbox.module

#!name=SandBox

#!desc=SandBox

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% api.sandbox.love

[Script]

SandBox=type=http-response,pattern=api.sandbox.love/accounts/current,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/sandbox.js