#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/songshift.module

#!name=SongShift

#!desc=SongShift

#!homepage=https://apptesters.org/scripting

#!author=AppTester

[MITM]

hostname = %APPEND% subscriptions.songshift.com

[Script]

SongShift=type=http-response,pattern=subscriptions.songshift.com/validate,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/songshift.js