#!url=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/modules/vsco.module

#!name=VSCO

#!desc=vsco解锁

#!homepage=https://whatshub.top

#!author=NobyDa

[MITM]

hostname= %APPEND% api.revenuecat.com

[Script]

VSCO=type=http-request,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/vsco.js

VSCO1=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,requires-body=1,script-path=https://raw.githubusercontent.com/starkayc/iOS/main/iap-spoof/scripts/vsco.js